# Generated by Django 5.2.5 on 2025-08-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('unknown', 'Unknown')], default='unknown')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('has_chronic_condition', models.BooleanField(default=False)),
                ('condition_controlled', models.BooleanField(default=False)),
                ('consent', models.BooleanField(default=False)),
                ('recent_tattoo_or_piercing', models.BooleanField(default=False)),
                ('ate_fatty_food', models.BooleanField(default=False)),
                ('ate_before_donation', models.BooleanField(default=True)),
                ('had_alcohol_last_24h', models.BooleanField(default=False)),
                ('sleep_hours', models.IntegerField(default=8)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='uploads/fingerprints/')),
                ('pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='core.participant')),
            ],
        ),
    ]
