# Generated by Django 5.2.5 on 2025-08-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_result_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ate_before_donation',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ate_fatty_food',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='condition_controlled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='had_alcohol_last_24h',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_chronic_condition',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='recent_tattoo_or_piercing',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='sleep_hours',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
