# Generated by Django 5.2.5 on 2025-08-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_participant_ate_before_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='willing_to_donate',
            field=models.BooleanField(default=False),
        ),
    ]
