# Generated by Django 5.2.5 on 2025-09-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
