# Generated by Django 5.2.5 on 2025-09-01 15:36

import core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('participant_data', models.JSONField()),
                ('diabetes_result', models.JSONField(blank=True, null=True)),
                ('blood_group_result', models.JSONField(blank=True, null=True)),
                ('fingerprints', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='participant',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
